// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var byState, data, load_visual, render_by_state, view_id;

    view_id = $("#view_selection a.btn.active").attr("id");
    byState = null;
    data = null;
    $("#view_selection a").click(function() {
      view_id = $(this).attr("id");
      $('#view_selection a').removeClass('active');
      return $(this).toggleClass("active");
    });
    render_by_state = function(data) {
      byState = new this.ByState('vis', d3.map(data).values(), 'PiYG');
      byState.create_vis();
      return byState.display();
    };
    load_visual = function(type) {
      switch (type) {
        case 'by_state':
          if (data === null) {
            return d3.json("crime.json", function(data) {
              return render_by_state(data);
            });
          }
          break;
        default:
          return render_by_state(data);
      }
    };
    return load_visual(view_id);
  });

}).call(this);
