// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var allStates, byState, load_visual, render_all_states, render_by_state, view_id;

    view_id = $("#view_selection a.btn.active").attr("id");
    byState = null;
    allStates = null;
    this.data = null;
    $("#view_selection a").click(function() {
      view_id = $(this).attr("id");
      $('#view_selection a').removeClass('active');
      $(this).toggleClass("active");
      return load_visual(view_id);
    });
    render_all_states = function() {
      allStates = new this.AllStates('vis', d3.map(this.data).values(), 'PiYG');
      allStates.create_vis();
      return allStates.display();
    };
    render_by_state = function() {
      byState = new this.StatesBreakDown('vis', d3.map(this.data).values(), 'PiYG');
      byState.create_vis();
      return byState.display();
    };
    load_visual = function(type) {
      switch (type) {
        case 'all_states':
          if (this.data == null) {
            return d3.json("crime.json", function(data) {
              this.data = data;
              return render_all_states();
            });
          } else {
            return render_all_states();
          }
          break;
        case 'by_state':
          return d3.json("crime.json", function(data) {
            this.data = data;
            return render_by_state();
          });
      }
    };
    return load_visual(view_id);
  });

}).call(this);
